### ISSUE TITLE
Local image files

### ISSUE THREAD

**Issue by tommygebru** [jboutiere/prj-rev-bwfs-dasmoto#6]
Suggestion: bring yourself up to speed with file management on your computer and coding environment.

Here are two excellent resources on dealing with files and linking to file paths 👍

https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Dealing_with_files

https://www.kirupa.com/html5/all_about_file_paths.htm

**Comment by jboutiere** [comment]
I think that was just my confusion with how GitHub would work. Originally, I had an images folder in my resources folder, but then I removed it and coded to link to Codecademy's site so the images would show. Now that I have used GitHub once, I can see that I would have been able to upload all of my assets and could have linked locally.

Thanks!
